export const Teachers = [
  {
    id: 1,
    name: 'Anna Kovacs',
    subject: 'Mathematics',
    homework: [],
    days: ['Monday', 'Wednesday'],
    avatar: 'teacher1.jpg',
  },
  {
    id: 2,
    name: 'Peter Szabo',
    subject: 'History',
    homework: [],
    days: ['Tuesday'],
    avatar: 'teacher2.jpg',
  },
  {
    id: 3,
    name: 'Julia Nagy',
    subject: 'Hungarian Literature',
    homework: [],
    days: ['Wednesday', 'Friday'],
    avatar: 'teacher3.jpg',
  },
  {
    id: 4,
    name: 'Gergely Toth',
    subject: 'Physics',
    homework: [],
    days: ['Thursday'],
    avatar: 'teacher4.jpg',
  },
  {
    id: 5,
    name: 'Emese Farkas',
    subject: 'Chemistry',
    homework: [],
    days: ['Friday'],
    avatar: 'teacher5.jpg',
  },
  {
    id: 6,
    name: 'Balazs Varga',
    subject: 'Computer Science',
    homework: [],
    days: ['Monday', 'Thursday'],
    avatar: 'teacher6.jpg',
  },
];
